### ISSUE TITLE
Models

### ISSUE THREAD

**Issue by Nirase** [Nirase/HvZCaseBackend#1]
## Definition of done
Models for every MVP table exists.

## TODO 
- [x] User
   - [x] user_id (pk)
   - [x] first_name
   - [x] last_name
- [x] Game
   - [x] game_id (pk)
   - [x] name
   - [x] game_state
- [x] Player
   - [x] player_id (pk)
   - [x] user_id (fk)
   - [x] game_id (fk)
   - [x] is_patient_zero
   - [x] is_human
   - [x] bite_code
- [x] Kill
   - [x] kill_id (pk)
   - [x] game_id (fk)
   - [x] killer_id (fk)
   - [x] victim_id (fk)
   - [x] time_of_death
