### ISSUE TITLE
Mission Model

### ISSUE THREAD

**Issue by Nirase** [Nirase/HvZCaseBackend#11]
## Definition of done
Defines a model for a mission object. 

## TODO 
- [ ] mission_id (PK)
- [ ] visible_to_humans
- [ ] visible_to_zombies
- [ ] start_date
- [ ] game_id (FK)
- [ ] end_date
- [ ] location
