### ISSUE TITLE
Squad Repository

### ISSUE THREAD

**Issue by Nirase** [Nirase/HvZCaseBackend#13]
## Definition of done
Squads can be created, updated and deleted

## TODO 
- [ ] User can create a squad
- [ ] User can join a squad
- [ ] Squad can be edited [ADMIN ONLY]
- [ ] Squad can be deleted [ADMIN ONLY]
