### ISSUE TITLE
Kill Full CRUD

### ISSUE THREAD

**Issue by Nirase** [Nirase/HvZCaseBackend#19]
## TODO
- [x] Update kill [ADMIN ONLY]
- [x] Delete kill [ADMIN ONLY]
- [x] Get all kills by game
