### ISSUE TITLE
Make Kill a subsection of Game

### ISSUE THREAD

**Issue by Nirase** [Nirase/HvZCaseBackend#21]
## TODO
- [ ] Kill url is instead of format "api/v1/game/<game_id>/kill" 
- [ ] Get all kills only fetches from the current game
- [ ] Get kill only fetches from the current game
