### ISSUE TITLE
Kill Repository

### ISSUE THREAD

**Issue by Nirase** [Nirase/HvZCaseBackend#5]
## Definition of done
User can add, update or delete kills. 

## TODO 
- [ ] Create kill [ADMIN AND ZOMBIES ONLY]
- [ ] Get all kills
- [ ] Get specific kill
