### ISSUE TITLE
Game Repository

### ISSUE THREAD

**Issue by Nirase** [Nirase/HvZCaseBackend#6]
## Definition of done 
User can create, update and delete games

## TODO
- [x] Fetch all games
- [x] Fetch one specific game [USER ONLY]
- [x] Create game [ADMIN ONLY]
- [ ] Update existing game [ADMIN ONLY]
- [ ] Delete existing game [ADMIN ONLY]
