### ISSUE TITLE
Chat Message Repository

### ISSUE THREAD

**Issue by Nirase** [Nirase/HvZCaseBackend#7]
## Definition of done 
Defines a model for a message

## TODO
- [ ] message_id (PK)
- [ ] List of messages
- [ ] sender_id (FK)
- [ ] time_of_message
